# Generated by Django 5.2.17 on 2026-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_web_shop_and_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
