# Generated by Django 5.2.17 on 2026-10-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(blank=True, db_default='', default='', upload_to='products/'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='app_order_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', 'ordered')), fields=['updated_at'], name='app_order_ordered_idx'),
        ),
    ]
