# Generated by Django 5.2.17 on 2026-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='working_hours',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
