# Generated by Django 5.2.17 on 2026-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_mobile_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('business', models.CharField(blank=True, default='', max_length=120)),
                ('kind', models.CharField(blank=True, choices=[('cafe', 'Kafe yoki restoran'), ('fastfood', 'Fast food'), ('shop', "Do'kon"), ('other', 'Boshqa')], default='', max_length=10)),
                ('comment', models.TextField(blank=True, default='', max_length=1000)),
                ('lang', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], default='uz', max_length=2)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('won', "Mijoz bo'ldi"), ('lost', 'Rad etildi')], default='new', max_length=10)),
                ('note', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
