# Generated by Django 5.2.17 on 2026-10-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0003_outbox'),
        ('app', '0020_order_indexes_product_thumb'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='outbox',
            name='adminbot_outbox_pending',
        ),
        migrations.AddIndex(
            model_name='outbox',
            index=models.Index(condition=models.Q(('attempts__lt', 5), ('sent_at__isnull', True)), fields=['id'], name='adminbot_outbox_due'),
        ),
    ]
